---

- name: Install required packages
  ansible.builtin.apt:
    name: '{{ (core__base_packages + core__packages) | flatten }}'
    state: 'present'
    install_recommends: false
    update_cache: true

- name: Install dotfiles for the default users
  ansible.builtin.include_tasks: dotfiles.yml

- name: Install dotfiles for root user
  ansible.builtin.include_tasks: dotfiles-root.yml
  when: core__with_root

- name: Install the resources files
  ansible.builtin.include_tasks: resources.yml
