---

- name: Update the apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install required packages
  ansible.builtin.apt:
    name: '{{ (core__base_packages + core__packages) | flatten }}'
    state: 'present'
    install_recommends: false

- name: Install dotfiles for the default users
  ansible.builtin.include_tasks: dotfiles-users.yml
  vars:
    core__getroot_method: 'sudo '

- name: Install dotfiles for root user
  ansible.builtin.include_tasks: dotfiles-root.yml
  when: core__with_root
  vars:
    core__getroot_method: ''

- name: Install and configure the firewall
  ansible.builtin.include_tasks: firewall.yml
  when: core__with_firewall

- name: Install play machine specificities
  ansible.builtin.include_tasks: play.yml
  when: core__with_play_machine
