---

play_machine:
  hosts:
    play:
      ansible_host: play.local
  vars:
    core__play_caddy_extra: |
      tls internal
    deploy__ssh_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    apparmor_profiles__build_cmd: 'make build\n\t./.build/prebuild --full --complain'
    apparmor_profiles__local_build_cmd: 'just complain'

all:
  vars:
    ansible_ssh_port: 22
    ansible_ssh_user: play
    ansible_become_pass: play

