---

play_machine:
  hosts:
    play:
      ansible_host: 192.168.122.158

donn_machine:
  hosts:
    donn:
      ansible_host: 192.168.122.111

all:
  vars:
    ansible_become_pass: play
    ansible_ssh_port: 22
    ansible_ssh_user: play
