---

# core

# Very common and basic configuration for all hosts

## General settings

# List of APT packages which are required by the role.
core__base_packages:
  - bash-completion
  - htop
  - qemu-guest-agent
  - systemd-coredump
  - systemd-oomd
  - unattended-upgrades

# List of APT packages to install on all hosts with the role.
core__packages: []


## Additional features

# Copy dotfiles to the root user home directory
core__with_root: true

# Apply play specificities
core__with_play_machine: true

# Install and configure the firewall
core__with_firewall: true

# Extra Caddy configuration
core__play_caddy_extra: ''
