---

stages:
  - lint
  - build
  - deploy


# Code Linter
# -----------

.ansible:
  stage: lint
  image: archlinux
  script:
    - pacman -Syu --noconfirm --noprogressbar ansible	ansible-lint
    - ansible-lint ansible/

check:
  stage: lint
  image: archlinux
  script:
    - mkdir -p tests
    - curl -sSL https://raw.githubusercontent.com/roddhjav/apparmor.d/refs/heads/main/tests/check.sh > check.sh
    - curl -sSL https://raw.githubusercontent.com/roddhjav/apparmor.d/refs/heads/main/tests/sbin.list > tests//sbin.list
    - bash check.sh

# Profiles Build
# --------------

build:
  stage: build
  image: archlinux
  script:
    - pacman -Syu --noconfirm --noprogressbar	go just
    - just build
