---

# List of APT packages to install on all hosts with the role.
core__packages:
  - caddy
  - curl
  - gcc
  - git
  - golang-go
  - jq
  - make
  - nano
  - nmap
  - python3
  - vim
  - wget

# Extra Caddy configuration
core__play_caddy_extra: |
  tls internal

# The SSH key to add to the deploy user's authorized_keys file.
deploy__ssh_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
