all:
  vars:
    deploy__ssh_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
    core__packages:
      - caddy
      - curl
      - gcc
      - git
      - golang-go
      - jq
      - make
      - nano
      - nmap
      - python3
      - vim
      - wget
