---

- name: Check for apparmor.d first install
  ansible.builtin.stat:
    path: /etc/ansible/facts/apparmor_profiles__installed
  register: apparmor_profiles__first_install

- name: Install requested packages
  ansible.builtin.package:
    name: '{{ (apparmor_profiles__base_packages + apparmor_profiles__packages) | flatten }}'
    state: 'present'
    install_recommends: false

- name: Enable journald audit
  ansible.builtin.service:
    name: systemd-journald-audit.socket
    enabled: true

- name: Ensure old apparmor cache directory is clean
  ansible.builtin.file:
    path: /var/cache/apparmor
    state: absent

- name: Configure apparmor for large set of profiles
  ansible.builtin.copy:
    src: parser.conf
    dest: /etc/apparmor/parser.conf
    mode: "0644"

- name: Ensure that Ansible will work with apparmor enabled
  ansible.builtin.copy:
    content: |
      owner @{HOME}/.ansible/tmp/ansible-tmp-*/* rw,
    dest: /etc/apparmor.d/local/sftp-server
    mode: "0644"

- name: Install local profiles
  ansible.builtin.include_tasks: local.yml
  when: apparmor_profiles__with_local
  tags: ['local']

- name: Install apparmor.d
  ansible.builtin.include_tasks: apparmord.yml
  when: apparmor_profiles__with_apparmord
  tags: ['apparmord']

- name: Configure AppArmor RBAC
  ansible.builtin.include_tasks: pam.yml
  when: apparmor_profiles__with_pam
  tags: ['pam']

- name: Restart apparmor
  ansible.builtin.systemd:
    name: apparmor
    state: restarted
    enabled: true
    no_block: false

- name: Reboot if required
  ansible.builtin.include_tasks: reboot.yml
