#cloud-config

hostname: ${hostname}

users:
  - name: ${username}
    passwd: ${passwd}
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
    lock_passwd: false
    sudo: ALL=(ALL) ALL

  - name: root
    plain_text_passwd: apparmor
    shell: /bin/bash
    lock_passwd: false

package_update: true
package_upgrade: true
package_reboot_if_required: false
