#cloud-config

hostname: ${hostname}

ssh_pwauth: true
users:
  - name: ${username}
    plain_text_passwd: ${password}
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
    lock_passwd: false
    sudo: ALL=(ALL) NOPASSWD:ALL

  - name: root
    plain_text_passwd: apparmor
    lock_passwd: false
    shell: /bin/bash

package_update: true
package_upgrade: true
package_reboot_if_required: false

write_files:

  - path: /etc/systemd/network/20-wired.network
    owner: 'root:root'
    permissions: '0644'
    content: |
      [Match]
      Name=en*

      [Network]
      DHCP=yes

      [DHCPv4]
      RouteMetric=10
