---

- name: Donn machine provisionning
  hosts: ['donn_machine']
  gather_facts: true
  become: true

  roles:

    - role: core
      tags: ['role::core', 'skip::core']

    - role: docker
      tags: ['role::docker', 'skip::docker']

    - role: docker.wazuh
      tags: ['role::wazuh', 'skip::wazuh']

    - role: apparmor-profiles
      tags: ['role::apparmor-profiles', 'skip::apparmor-profiles']

    - role: apparmor-local
      tags: ['role::apparmor-local', 'skip::apparmor-local']
