---

- name: Play machine provisionning
  hosts: ['play_machine']
  gather_facts: true
  become: true
  vars:
    deploy__ssh_key: "{{ lookup('file', '~/.ssh/id_deploy.pub') }}"
    core__with_root: true
    core__packages:
      - caddy
      - curl
      - gcc
      - git
      - golang-go
      - jq
      - make
      - nano
      - nmap
      - python3
      - systemd-coredump
      - systemd-oomd
      - vim
      - wget

  roles:

    - role: core
      tags: ['role::core']

    - role: deploy
      tags: ['role::deploy']

    - role: apparmor-profiles
      tags: ['role::apparmor-profiles']

    - role: apparmor-local
      tags: ['role::apparmor-local']
