---

- name: Play machine provisionning
  hosts: ['play_machine']
  gather_facts: true
  become: true

  roles:

    - role: apparmor-profiles
      tags: ['role::apparmor-profiles']

    - role: core
      tags: ['role::core']

    - role: deploy
      tags: ['role::deploy']

