---

- name: Initialize the Hugo based static website
  hosts: ['play_machine']
  gather_facts: false
  become: true
  vars:
    site_path: '{{ inventory_dir | realpath | dirname | dirname | dirname }}/site/'

  tasks:

    - name: Build the Hugo website
      ansible.builtin.command:
        chdir: '{{ site_path }}'
        cmd: 'hugo build'
        creates: '{{ site_path }}/public'
      delegate_to: localhost
      become: false

    - name: Ensure caddy web root is clean
      ansible.builtin.file:
        dest: /srv/www/
        state: absent

    - name: Create a new Caddy web root
      ansible.builtin.file:
        dest: /srv/www/public
        state: directory
        mode: "0755"

    - name: Deploy the Hugo website
      ansible.builtin.copy:
        src: '{{ site_path }}/public/'
        dest: /srv/www/public/
        mode: "0644"

    - name: Start Caddy
      ansible.builtin.service:
        name: caddy
        state: started
        enabled: true
