---

- name: Initialize the Hugo based static website
  hosts: ['play']
  gather_facts: false
  become: true
  vars:
    site_path: '{{ inventory_dir | realpath | dirname | dirname }}/site/public'

  tasks:

    - name: Ensure caddy web root is clean
      ansible.builtin.file:
        dest: /srv/www/public
        state: absent

    - name: Create a new Caddy web root
      ansible.builtin.file:
        dest: /srv/www/public
        state: directory
        mode: "0755"

    - name: Deploy the Hugo website
      ansible.builtin.copy:
        src: '{{ site_path }}'
        dest: /srv/www/
        mode: "0644"

    - name: Start Caddy
      ansible.builtin.service:
        name: caddy
        state: started
        enabled: true
