---

- name: Add Crowdsec APT key
  ansible.builtin.shell:
    executable: /bin/bash
    cmd: |
      set -euo pipefail
      curl -fsSL https://packagecloud.io/crowdsec/crowdsec/gpgkey | gpg --dearmor -o /usr/share/keyrings/crowdsec_crowdsec-archive-keyring.gpg
  args:
    creates: /usr/share/keyrings/crowdsec_crowdsec-archive-keyring.gpg

- name: Add Crowdsec APT repository
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/usr/share/keyrings/crowdsec_crowdsec-archive-keyring.gpg] https://packagecloud.io/crowdsec/crowdsec/ubuntu jammy main'
    state: present

- name: Install requested packages
  ansible.builtin.package:
    name: '{{ q("flattened", (crowdsec__base_packages
                              + crowdsec__packages)) }}'
    state: 'present'
    update_cache: true
    install_recommends: false

- name: Install Crowdsec collections
  ansible.builtin.command:
    cmd: "cscli collections install {{ item }}"
  with_items: "{{ crowdsec__collections_list }}"
  register: collections_install_result
  changed_when: "'overwrite' not in collections_install_result.stderr"
  when: crowdsec__collections_list | length > 0
  notify: Restart crowdsec

- name: Enroll instance to console
  ansible.builtin.command:
    cmd: "cscli console enroll {{ crowdsec__console_token }}"
  when: crowdsec__console_token is defined
