---

- name: Get latest ctop version
  community.general.github_release:
    user: bcicen
    repo: ctop
    action: latest_release
  register: ctop__release

- name: Get latest ctop version
  ansible.builtin.set_fact:
    ctop__version: '{{ ctop__release["tag"].split("v")[1] }}'

- name: Get latest lazydocker release
  community.general.github_release:
    user: jesseduffield
    repo: lazydocker
    action: latest_release
  register: lazydocker__release

- name: Get latest lazydocker version
  ansible.builtin.set_fact:
    lazydocker__version: '{{ lazydocker__release["tag"].split("v")[1] }}'

- name: Install ctop
  ansible.builtin.get_url:
    url: 'https://github.com/bcicen/ctop/releases/download/v{{ ctop__version }}/ctop-{{ ctop__version }}-linux-amd64'
    checksum: 'sha256:https://github.com/bcicen/ctop/releases/download/v{{ ctop__version }}/sha256sums.txt'
    dest: /usr/bin/ctop
    owner: root
    group: root
    mode: "0755"

- name: Retrieve lazydocker
  ansible.builtin.get_url:
    url: 'https://github.com/jesseduffield/lazydocker/releases/download/v{{ lazydocker__version }}/lazydocker_{{ lazydocker__version }}_Linux_x86_64.tar.gz'
    checksum: 'sha256:https://github.com/jesseduffield/lazydocker/releases/download/v{{ lazydocker__version }}/checksums.txt'
    dest: /tmp/
    mode: "0644"

- name: Extract lazydocker
  ansible.builtin.unarchive:
    src: /tmp/lazydocker_{{ lazydocker__version }}_Linux_x86_64.tar.gz
    dest: /tmp/
    remote_src: true

- name: Install lazydocker
  ansible.builtin.copy:
    src: /tmp/lazydocker
    dest: /usr/bin/lazydocker
    owner: root
    group: root
    mode: "0755"
    remote_src: true
