---

# Documentation:
# - https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html

- name: Increase max_map_count on your host
  ansible.builtin.copy:
    src: sysctl/90-wazuh.conf
    dest: /usr/lib/sysctl.d
    mode: "0644"

- name: Ensure Wazuh configuration directory exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  with_items:
    - /etc/wazuh
    - /etc/wazuh/wazuh_indexer_ssl_certs

- name: Ensure Wazuh configuration files exist
  ansible.builtin.copy:
    src: "wazuh/"
    dest: "/etc/wazuh"
    mode: "0644"

- name: Create internal network
  community.docker.docker_network:
    name: wazuh-network
    driver: bridge

- name: Ensure docker volumes exist
  community.docker.docker_volume:
    name: "{{ item }}"
  with_items:
    - wazuh_api_configuration
    - wazuh_etc
    - wazuh_logs
    - wazuh_queue
    - wazuh_var_multigroups
    - wazuh_integrations
    - wazuh_active_response
    - wazuh_agentless
    - wazuh_wodles
    - filebeat_etc
    - filebeat_var
    - wazuh-indexer-data
    - wazuh-dashboard-config
    - wazuh-dashboard-custom

# TODO: Only run once
# - name: Install Wazuh cert tool
#   community.docker.docker_container:
#     name: wazuh-certs-generator
#     image: wazuh/wazuh-certs-generator:0.0.2
#     hostname: wazuh-certs-generator
#     auto_remove: true
#     volumes:
#       - /etc/wazuh/wazuh_indexer_ssl_certs/:/certificates/
#       - /etc/wazuh/certs.yml:/config/certs.yml
#   # creates: /etc/wazuh/wazuh_indexer_ssl_certs/root-ca-manager.pem

- name: Install Wazuh Manager
  community.docker.docker_container:
    name: wazuh.manager
    detach: true
    image: 'wazuh/wazuh-manager:{{ wazuh__version }}'
    hostname: wazuh.manager
    pull: true
    state: started
    restart: true
    restart_policy: always
    ulimits:
      - memlock:-1:-1
      - nofile:655360:655360
    ports:
      - "1514:1514"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"
    volumes:
      - wazuh_api_configuration:/var/ossec/api/configuration
      - wazuh_etc:/var/ossec/etc
      - wazuh_logs:/var/ossec/logs
      - wazuh_queue:/var/ossec/queue
      - wazuh_var_multigroups:/var/ossec/var/multigroups
      - wazuh_integrations:/var/ossec/integrations
      - wazuh_active_response:/var/ossec/active-response/bin
      - wazuh_agentless:/var/ossec/agentless
      - wazuh_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat
      - /etc/wazuh/wazuh_indexer_ssl_certs/root-ca-manager.pem:/etc/ssl/root-ca.pem
      - /etc/wazuh/wazuh_indexer_ssl_certs/wazuh.manager.pem:/etc/ssl/filebeat.pem
      - /etc/wazuh/wazuh_indexer_ssl_certs/wazuh.manager-key.pem:/etc/ssl/filebeat.key
      - /etc/wazuh/wazuh_cluster/wazuh_manager.conf:/wazuh-config-mount/etc/ossec.conf
    networks:
      - name: wazuh-network
    env:
      INDEXER_URL: https://wazuh.indexer:9200
      INDEXER_USERNAME: '{{ wazuh__indexer_username }}'
      INDEXER_PASSWORD: '{{ wazuh__indexer_password }}'
      FILEBEAT_SSL_VERIFICATION_MODE: full
      SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
      SSL_CERTIFICATE: /etc/ssl/filebeat.pem
      SSL_KEY: /etc/ssl/filebeat.key
      API_USERNAME: '{{ wazuh__api_username }}'
      API_PASSWORD: '{{ wazuh__api_password }}'

- name: Install Wazuh Indexer
  community.docker.docker_container:
    name: wazuh.indexer
    detach: true
    image: 'wazuh/wazuh-indexer:{{ wazuh__version }}'
    hostname: wazuh.indexer
    pull: true
    state: started
    restart: true
    restart_policy: always
    ulimits:
      - memlock:-1:-1
      - nofile:65536:65536
    ports:
      - "9200:9200"
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - /etc/wazuh/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - /etc/wazuh/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - /etc/wazuh/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - /etc/wazuh/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - /etc/wazuh/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - /etc/wazuh/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - /etc/wazuh/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
    networks:
      - name: wazuh-network
    env:
      OPENSEARCH_JAVA_OPTS: '-Xms1g -Xmx1g'

- name: Install Wazuh Dashboard
  community.docker.docker_container:
    name: wazuh.dashboard
    detach: true
    image: 'wazuh/wazuh-dashboard:{{ wazuh__version }}'
    hostname: wazuh.dashboard
    pull: true
    state: started
    restart: true
    restart_policy: always
    ports:
      - 443:5601
    volumes:
      - /etc/wazuh/wazuh_indexer_ssl_certs/wazuh.dashboard.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
      - /etc/wazuh/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem:/usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
      - /etc/wazuh/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-dashboard/certs/root-ca.pem
      - /etc/wazuh/wazuh_dashboard/opensearch_dashboards.yml:/usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
      - /etc/wazuh/wazuh_dashboard/wazuh.yml:/usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
      - wazuh-dashboard-config:/usr/share/wazuh-dashboard/data/wazuh/config
      - wazuh-dashboard-custom:/usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
    networks:
      - name: wazuh-network
    env:
      WAZUH_API_URL: https://wazuh.manager
      INDEXER_USERNAME: '{{ wazuh__indexer_username }}'
      INDEXER_PASSWORD: '{{ wazuh__indexer_password }}'
      DASHBOARD_USERNAME: '{{ wazuh__dashboard_username }}'
      DASHBOARD_PASSWORD: '{{ wazuh__dashboard_password }}'
      API_USERNAME: '{{ wazuh__api_username }}'
      API_PASSWORD: '{{ wazuh__api_password }}'
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
