---

# deploy

# Create the deploy user for various server deployment tasks.
# This user will then be confined using the role_deploy profile.

## General

# The username of the deploy user to create.
deploy__user: deploy

# The SSH key to add to the deploy user's authorized_keys file.
deploy__ssh_key: ''

# A list of paths that the deploy user is allowed to write to.
deploy__allow_paths:
  - /var/www/public

## Installation, APT packages

# List of APT packages which are required by the role.
deploy__base_packages:
  - acl

# List of APT packages to install on all hosts with the role.
deploy__packages: []
