---

play_machine:
  hosts:
    play:
      ansible_host: play.pujol.io

donn_machine:
  hosts:
    donn:
      ansible_host: donn.pujol.xyz

all:
  vars:
    ansible_ssh_port: 22
    ansible_ssh_user: play
    ansible_become_pass: '{{ lookup("passwordstore", "inventory/production/" + ansible_host + "/password") }}'
    passwordstore: .secret-store

