---

play_machine:
  hosts:
    play:
      ansible_host: play.pujol.io
      # Required on initial setup only:
      # apparmor_profiles__build_cmd: 'make build\n\t./.build/prebuild --full --complain'
      # apparmor_profiles__local_build_cmd: 'just complain'

all:
  vars:
    ansible_ssh_port: 22
    ansible_ssh_user: play
    ansible_become_pass: '{{ lookup("passwordstore", "inventory/production/" + ansible_host + "/password") }}'
    passwordstore: .secret-store
